### ISSUE TITLE
Refresh doesn't work for fuse mounted filesystem

### ISSUE THREAD

**Issue by kuznetsss** [kyazdani42/nvim-tree.lua#425]
Hello! Thank you for the plugin, it's very usefull!

Nvim-tree doesn't update file list when I'm working with a directory mounted as fuse filesystem. For example, I can't see actual files tree after moving/creating files and even manual refresh doesn't help.

**Comment by kyazdani42** [comment]
Hello :)
I will take a look at this, i've never worked with a fuse filesystem, i'm not too sure how to do that. I'll do some research and come back here

**Comment by Louis-Amas** [comment]
Hi doesn't refresh since the last version for me. on normal filesystem

**Comment by kyazdani42** [comment]
more informations please, does work for me.

**Comment by lvim-tech** [comment]
Not work...
![nvim-tree_error](https://user-images.githubusercontent.com/82431193/120885336-095fde00-c5f1-11eb-85f8-ae0ee2dd4bf5.png)

**Comment by kyazdani42** [comment]
@lvim-tech not related. Please refer the the right issue.
As for the fuse issue, seems like a libuv threadpool related stuff. I'm not sure how i can manage this properly but if you set `UV_THREADPOOL_SIZE` to a high values (10000, 100000), you might be able to see the files and directories inside an fuse filesystem.

**Comment by vlstv** [comment]
> Hi doesn't refresh since the last version for me. on normal filesystem

same for me

**Comment by strogiyotec** [comment]
Hey, it doesn't display a new created files on the tree(I pressed 'a' was promoted to add a new file, file was created but Nvim-Tree doesn't display it ). I tried to call `:NvimTreeRefresh` no difference , I am using the latest version

**Comment by kyazdani42** [comment]
@vlstv @lvim-tech @strogiyotec if your issue concerns normal filesystem, please open a new issue (with more informations like your neovim and nvim-tree versions, alongside a minimal init.vim/lua file and if you can, reproduction steps).

**Comment by strogiyotec** [comment]
Sure I will raise another one

**Comment by Louis-Amas** [comment]
https://github.com/kyazdani42/nvim-tree.lua/commit/ef570074e0f73e59e24d41fba5db3b2db0fdc58c

**Comment by kyazdani42** [comment]
not sure why but i think your version is not up to date. Calling `lua print(vim.v.exiting)` prints `vim.NIL`. A commit introduced that a few weeks ago.

**Comment by Louis-Amas** [comment]
Yes you are right, but you could support both version. Because not everybody will have the last version

**Comment by kyazdani42** [comment]
supporting many versions of neovim would be hard when it changes so frequently. 0.5 is not yet out i believe and is still in nightly mode so you should expect breakage from time to time, and running nightly means updating frequently :)
PS: it is also stated in the readme that you need neovim nightly

**Comment by Louis-Amas** [comment]
Ok I understand better now. I hope I will help other just update to nvim nightly last version and the problem is not there anymore.

**Comment by kuznetsss** [comment]
It seems my issue with fuse file system was caused by outdated nvim. Now it works fine.

**Comment by kyazdani42** [comment]
thanks :) well for me a fuse file system is not working properly but i don't know how to fix that well yet. I'll leave it open for now

**Comment by kyazdani42** [comment]
fixed in 7abec5e5943

**Comment by andrzej-mag** [comment]
Problem still exists in my case unfortunately.
Nvim-tree window content always disappears when for example writing a file in a git controlled directory. Running any `NvimTree*` commands or setting `UV_THREADPOOL_SIZE` has no effect.

Tested with:
```shell
>nvim -v
NVIM v0.6.0-dev+32-ge43dbfdd0
# and:
>nvim -v
NVIM v0.5.0

> sshfs -V
SSHFS version 3.7.1
FUSE library version 3.10.3
using FUSE kernel interface version 7.31
fusermount3 version: 3.10.3
```
Everything works perfectly with local files.

Many thanks for creating such a great plugin!

**Comment by kyazdani42** [comment]
could not reproduce though :/ it works perfectly on my machine, i have the same sshfs version and nvim version. Which nvim-tree version are you using ?

**Comment by andrzej-mag** [comment]
I do not see any strict versioning in Nvim-tree. Plugin is installed with packer: `use {'kyazdani42/nvim-tree.lua'}`, so it is a `master` branch.

Nvim-tree config:
```
local g = vim.g

g.nvim_tree_side = 'left' -- left by default
g.nvim_tree_width = 35 -- 30 by default, can be width_in_columns or 'width_in_percent%'
g.nvim_tree_gitignore = 0 -- 0 by default
g.nvim_tree_auto_open = 0 -- 0 by default, opens the tree when typing `vim $DIR` or `vim`
g.nvim_tree_auto_close = 0 -- 0 by default, closes the tree when it's the last window
-- g.nvim_tree_auto_ignore_ft = { 'startify', 'dashboard' } -- empty by default, don't auto open tree on specific filetypes.
g.nvim_tree_quit_on_open = 0 -- 0 by default, closes the tree when you open a file
g.nvim_tree_follow = 1 -- 0 by default, this option allows the cursor to be updated when entering a buffer
g.nvim_tree_indent_markers = 1 -- 0 by default, this option shows indent markers when folders are open
g.nvim_tree_hide_dotfiles = 0 -- 0 by default, this option hides files and folders starting with a dot `.`
g.nvim_tree_git_hl = 1 -- 0 by default, will enable file highlight for git attributes (can be used without the icons).
g.nvim_tree_highlight_opened_files = 1 -- 0 by default, will enable folder and file icon highlight for opened files/directories.
g.nvim_tree_root_folder_modifier = ':~' -- This is the default. See :help filename-modifiers for more options
g.nvim_tree_tab_open = 0 -- 0 by default, will open the tree when entering a new tab and the tree was previously open
g.nvim_tree_auto_resize = 0 -- 1 by default, will resize the tree to its saved width when opening a file
g.nvim_tree_add_trailing = 1 -- 0 by default, append a trailing slash to folder names
g.nvim_tree_group_empty = 1 -- 0 by default, compact folders that only contain a single folder into one node in the file tree
g.nvim_tree_lsp_diagnostics = 1 -- 0 by default, will show lsp diagnostics in the signcolumn. See :help nvim_tree_lsp_diagnostics
g.nvim_tree_disable_window_picker = 0 -- 0 by default, will disable the window picker.
g.nvim_tree_hijack_cursor = 1 -- 1 by default, when moving cursor in the tree, will position the cursor at the start of the file on the current line
g.nvim_tree_icon_padding = ' ' -- one space by default, used for rendering the space between the icon and the filename. Use with caution, it could break rendering if you set an empty string depending on your font.
g.nvim_tree_update_cwd = 0 -- 0 by default, will update the tree cwd when changing nvim's directory (DirChanged event). Behaves strangely with autochdir set.
g.nvim_tree_special_files = {}
g.nvim_tree_ignore = {
  '.git',
  'node_modules',
  '.cache',
  '.elixir_ls',
  '_build',
  'mix.lock',
  'yarn.lock',
  '.formatter.exs',
  'deps',
  '.iex.exs',
  'doc'
}
g.nvim_tree_show_icons = {
  git = 1,
  folders = 0,
  files = 0,
  folder_arrows = 1
}
g.nvim_tree_icons = {
  lsp = {
    hint = "H",
    info = "I",
    warning = "W",
    error = "E"
  },
  git = {
    unstaged = "u ",
    staged = "s ",
    unmerged = "m ",
    renamed = "r ",
    untracked = "n ",
    deleted = "d ",
    ignored = "i "
  }
}
```

**Comment by kyazdani42** [comment]
could not reproduce with your config, my sshfs folder is rendering just fine. I have the same version for everything so it might be related to something else ?

**Comment by andrzej-mag** [comment]
Most probably f178c8c8c5cb994326578a24d3296dde6f2e9bd3 fixed disappearing content for git events.
I believe that similar fix is required for `LspDiagnostics*` - I still have a problem here.
When I write `*.md` file everything works (no LSP). When writing to a file where LSP is involved: tree content disappears.

**Comment by andrzej-mag** [comment]
Maybe this observation will help:
1. Write to “LSP file”: tree content vanishes.  `NvimTreeRefresh` does not help.
2. Write again, but this time to non-“LSP file”: tree content appears again.

**Comment by kyazdani42** [comment]
that's strange, i have no rendering based on lsp so it should not affect the content :/

**Comment by andrzej-mag** [comment]
I am not sure how can I help to reproduce this. Problem happens only when working with sshfs mounted projects: tree content disappears as I described earlier. If I open the same project but with nvim running remotely over ssh, there are no any issues.
lsp_diagnostics and git_hl are enabled:
```
g.nvim_tree_lsp_diagnostics = 1
g.nvim_tree_git_hl = 1
```

**Comment by kyazdani42** [comment]
hum you don't have to say more, just tested i don't think it's related to lsp, it just happens randomly on refresh :/

**Comment by kyazdani42** [comment]
should be fixed, forgot to update the refresh code

**Comment by andrzej-mag** [comment]
Confirmed, 98f372eddd1a68e5967504fb103fdafd120c24f2 solves problem of a disappearing tree content for sshfs mounted projects.
Thank you so much for great plugin!
