### ISSUE TITLE
g? bit odd

### ISSUE THREAD

**Issue by gegoune** [kyazdani42/nvim-tree.lua#492]
Sorry about the title. ;)

with
```lua
vim.g.nvim_tree_bindings = {
  { key = "<C-s>", cb = tree_callback "split" },
  { key = "<C-x>", cb = "" },
  { key = "h", cb = tree_callback "close_node" },
  { key = { "<CR>", "l" }, cb = tree_callback "edit" },
}
```
I get this from `g?` (excerpt):
```
<C-x> : 'split'           
<C-s> : 'split'           
<C-t> : 'tabnew'          
    H : 'toggle_dotfiles' 
   g? : 'toggle_help'     
    I : 'toggle_ignored'  
<C-v> : 'vsplit'          
<C-x> : ""                
```

Can I somehow remove `<C-x>` mapping completely?
If not, could help only list effective key maps?

**Comment by kyazdani42** [comment]
we could filter out empty mappings indeed. Not sure what you mean by 'effective' ?

**Comment by gegoune** [comment]
What I meant is that `<C-x>` by default is mapped to `'split'` which I then override with empty string. I do see both, but default mapping is no longer there yet still on the list. Hope it makes bit more sense. :)

**Comment by kyazdani42** [comment]
i see, you could submit a PR i have to say i don't use this help view ^^'

**Comment by gegoune** [comment]
With new mapping system in place, is it possible to delete mapping from default? Maybe setting it to `nil`? (Tried that, didn't work.)

**Comment by kyazdani42** [comment]
done in 1b04082872aaa4b `1.4.12`

**Comment by gegoune** [comment]
Thanks! I am still seeing it though, so probably something doesn't work properly:

```lua
require('nvim-tree').setup {
  view = {
    mappings = {
      list = {
        { key = '<C-s>', cb = callback 'split' },
        { key = '<C-x>', cb = nil },
      },
    },
  },
}
```

 `<C-x> : 'split'` is still in `g?` help window.

**Comment by kyazdani42** [comment]
set an empty string instead otherwise it will not override it.

**Comment by gegoune** [comment]
Tried that too (should have mention it in previous post), still shows up there. It's not critical at all! :)

**Comment by kyazdani42** [comment]
woups indeed, i'll fix that later on

**Comment by kyazdani42** [comment]
fixed in `1.4.16` (cd7be73)

**Comment by gegoune** [comment]
It works now, thanks a lot!
