### ISSUE TITLE
Session conflict when setting buffer name

### ISSUE THREAD

**Issue by ahmedkhalf** [kyazdani42/nvim-tree.lua#591]
Reproduction:

1. Save the current session when nvim-tree is open. `:mksession!`
2. Load session using `nvim -S Session.vim`

You now have the following error.
```
"NvimTree" [Not edited] --No lines in buffer--                                                                                                                                                
Error detected while processing CursorMoved Autocommands for "NvimTree":                                                                                                                      
E5108: Error executing lua ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:102: Expected 1 argument                                                                               
Press ENTER or type command to continue
```
Furthermore, nvim_tree is not open, but it should be open since session was saved while open.
Furthermore, entries are doubled as in: #590

**Comment by kyazdani42** [comment]
I've addressed the first issue in 0a178d17bc7a1c56cc. The second one is quite tricky because the session tries to load a buffer named NvimTree although it's already loaded on startup.
The setup refactoring should be able to fix this issue by deferring the setup call `after` the session file has loaded. I haven't found a way to detect if vim is opening through a vim session though.

**Comment by ahmedkhalf** [comment]
> haven't found a way to detect if vim is opening through a vim session though.

perhaps a hackish way would be to check for `-S` in `v:argv`

**Comment by kyazdani42** [comment]
should be fixed in 1.1.5 (4cc2abe)

**Comment by ahmedkhalf** [comment]
I believe this was wrongly closed @kyazdani42 .

As this issue is still present:
https://github.com/kyazdani42/nvim-tree.lua/issues/591#issuecomment-906984527

**Comment by kyazdani42** [comment]
indeed, sorry though this was fixed :smile:

**Comment by ahmedkhalf** [comment]
> indeed, sorry thought this was fixed smile

After the recent updates, the second issue is now fixed, but now a third issue is born :(. When I save the session with nvim-tree open, it does not restore my vim with nvim-tree, it is instead closed.

**Comment by kyazdani42** [comment]
because the setup/entry is not working with sessions at all. I have to use 
```
						*SessionLoad-variable*
While the session file is loading the SessionLoad global variable is set to 1.
Plugins can use this to postpone some work until the SessionLoadPost event is
triggered.
```
I will probably take a look into it soon

**Comment by ahmedkhalf** [comment]
thank you! but sorry at the same time :(, issue #2 has been reintroduced when having nvim-tree open when dashboard.nvim is open.

**Comment by kyazdani42** [comment]
i'll check this out once i merge the setup refactoring, i don't want more code conflicts before. I'll merge the setup thing tomorrow i think, and will fix the session stuff altogether because it's quite annoying :)

**Comment by AlexW00** [comment]
having the same issue.

**Comment by kyazdani42** [comment]
@AlexW00 which one exactly ?

**Comment by AlexW00** [comment]
> @AlexW00 which one exactly ?

The one mentioned in the OP: "Empty buffer" warning when re opening a saved session with an open NvimTree buffer.

**Comment by AntonellaCoder** [comment]
I have an error in line 39 when loading a session where nvim-tree is in.
```
   5 exe 'vert 1resiz
   4 exe 'vert 2resiz
   3 exe 'vert 3resiz
   2 argglobal
   1 enew
 39  file NvimTree
   1 balt session.vim
   2 setlocal fdm=man
   3 setlocal fde=0
   4 setlocal fmr={{{
   5 setlocal fdi=#
   6 setlocal fdl=0
   7 setlocal fml=1
   8 setlocal fdn=20
   9 setlocal nofen
  10 lcd ~/.dotfiles
```

**Comment by kyazdani42** [comment]
I'll be working on this in the next few days, in the meantime, you should call `:set mksession!` after closing nvim-tree.

**Comment by man9ourah** [comment]
Just an FYI, the fix in e5aff47 broke lazy loading nvim-tree on keys/cmds, i.e. with:
```lua
      use {
        'kyazdani42/nvim-tree.lua',
        keys = {{"n", "<c-n>"}},
        cmd = {"NvimTreeToggle"},
        config = function ()
          require("plugins.nvim-tree")
        end
      }
```

Since the View setup() is now scheduled on the key press that opens nvim-tree, causing an error like:
```
E5108: Error executing lua ...ite/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/view.lua:211: attempt to concatenate local 'move_to' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/view.lua:211: in function 'replace_window'
        ...ite/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/view.lua:218: in function 'open_window'
        ...ite/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/view.lua:237: in function 'open'
        ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:109: in function 'open'
        ...vim/site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree.lua:33: in function 'toggle'
        [string ":lua"]:1: in main chunk
```
i.e. View table is still empty when used.

While I dont really mind changing my lazy loading setup to something like VimEnter, I just thought to write this notice here.

**Comment by kyazdani42** [comment]
@man9ourah should be fixed, in latest master, although there is a weird glitch when you have auto_open set to false and lazy loading, then toggling the tree.
I should be able to rewrite the setup in the next week or two, depending on some other refactoring i need to do 1st.

**Comment by man9ourah** [comment]
Thanks for your work.. It is always appreciated.

**Comment by asteroidalaz** [comment]
Is this bug fixed? I am still getting this error.

**Comment by alex-courtis** [comment]
> Is this bug fixed? I am still getting this error.

Please raise a [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with a minimal configuration so that we may reproduce.

**Comment by andisab** [comment]
Fwiw, if NvimTree is open when I save a session to a named file, I still get the error when I return and load the session. Was able to avoid by doing `:mks! ~/.vim/session.vim` with Nvim-tree closed. If nvim-tree is not in the buffer list, no error.
