### ISSUE TITLE
Stoped playing nicely with Dirvish

### ISSUE THREAD

**Issue by VVKot** [kyazdani42/nvim-tree.lua#611]
Plugin current overrides/interferes with Dirvish's `-` mapping. Specifically, I am used to pressing `-` to quickly open a listing of current directory - that started taking me to parent directory instead, even though NvimTree  at that point!

Disabling all keybindings helps but only partially - at some point pressing `-` inside Dirvish opens up a buffer on the left (where tree usually is located) with the size that I configured for the tree.

**Comment by ggsalas** [comment]
Seems [this is the PR that creates this bug](https://github.com/kyazdani42/nvim-tree.lua/commit/3bac5633e1f7e778d0bcb54a2ab612d5fbce1248). If you go one commit before `git checkout dc630d199a0ad593036d193232c6b338aa0407e3` the bug is fixed. 

I hope this helps.

**Comment by VVKot** [comment]
@kyazdani42 any chance we can have a flag to disable this behavior while it is not fixed?

**Comment by kyazdani42** [comment]
fixed in `1.4.8` (928294407809). Use `update_to_buf_dir = false` in the setup options to disable the feature.
