### ISSUE TITLE
[bug] update_cwd unwanted change to root on first buffer enter

### ISSUE THREAD

**Issue by alex-courtis** [kyazdani42/nvim-tree.lua#974]
**OS**
`Arch Linux 5.16.8-arch1-1`

**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**
0f7da14

**Describe the bug**
After changing to a subdirectory for the first time, entering a buffer results in nvim-tree changing to that parent directory, however its lcd is still the subdirectory.

Subsequest nvim-tree directory changes and buffer enters result in no further unwanted directory changes.

**To Reproduce**
empty nvim configuration, no plugins othen than nvim-tree

```lua
tree.setup {
	update_cwd = true,
}
```
NvimTreeOpen
change to a subdirectory
select the window with the empty, default buffer
nvim-tree changes its directory back to the root, however pwd indicates that its local directory is still the above subdirectory

[![asciicast](https://asciinema.org/a/468669.svg)](https://asciinema.org/a/468669)

**Expected behavior**
nvim-tree's directory is not changed.

**Comment by kyazdani42** [comment]
does #967 fix that ?

**Comment by alex-courtis** [comment]
Unfortunately no; still occurring at 48818d5

**Comment by kyazdani42** [comment]
should be fixed in latest master, can you confirm ?

**Comment by alex-courtis** [comment]
Still occurring, I am sorry to say:

```sh
mkdir /tmp/974
cd /tmp/974
mkdir dir
vi
```
`NvimTreeOpen`
`<C-W> h`
select dir
`<C-]>`
`:pwd` shows `/tmp/974/dir`
`<C-W> l`
nvim-tree has changed directory to `/tmp/974`
`<C-W> h`
`:pwd` still shows `/tmp/974/dir`
select dir
`<C-]>`
`<C-W> l`
now nvim-tree stays in `/tmp/974/dir`

**Comment by alex-courtis** [comment]
Please don't be overly concerned with some of these issues. They are small, and I raised them with the intention to fix them myself.

**Comment by icaroponce** [comment]
Facing the same issue with 

```
tree.setup {
  update_focused_file = { enable = true }
}
```

**Comment by alex-courtis** [comment]
No longer occurring at ad2802d, closing.

I note that behaviour has changed at 6da7467, prior to the above:
nvim-tree will wipe the [no name] buffer on NvimTreeOpen, even if it is modified
Raising separate issue.

**Comment by alex-courtis** [comment]
Raised #1007
